[package]
name = "rperf"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12"
thiserror = "2.0"
tokio = { version = "1.43", features = ["full"] }
warp = "0.3"

[dev-dependencies]
wiremock = "0.6"
